name: "Pull Request Template"
description: "Fill out this template by replacing the placeholders."
title: "PR: {{ related issue title }}"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: "## 관련 이슈\nPlease replace `#issue_number` with the actual issue number."

  - type: textarea
    id: issue_number
    attributes:
      label: "Related Issue Number"
      description: "Type the issue number related to this PR."
      placeholder: "#issue_number"
      value: "close #"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 작업 내용 :technologist:"

  - type: textarea
    id: task_details
    attributes:
      label: "Task Details"
      description: "Describe the tasks you completed in this PR."
      placeholder: "List your tasks here."
      render: markdown
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## PR 포인트 :speech_balloon:"

  - type: textarea
    id: pr_points
    attributes:
      label: "PR Points"
      description: "Any specific areas you want the reviewer to focus on?"
      placeholder: "Add your points here."
      render: markdown

  - type: markdown
    attributes:
      value: "## 알게된 점 :rocket:"

  - type: textarea
    id: learning_points
    attributes:
      label: "Learnings"
      description: "What did you learn while working on this issue?"
      placeholder: "Share your learnings here."
      render: markdown

  - type: markdown
    attributes:
      value: "## 스크린샷 (선택)"

  - type: markdown
    attributes:
      value: "Include screenshots of your work if applicable."