import {
	IcPhoneBlack16,
	IcBottleBlack16,
	IcBeautyBlack16,
	IcPaintBlack16,
	IcBagBlack16,
	IcRefrigeratorBlack16,
	IcHomeBlack16,
	IcHelmetBlack16,
	IcBallBlack16,
	IcJewelBlack16,
	IcGameBlack16,
	IcWatchBlack16,
	IcUnderwearBlack16,
} from '@assets/icons/index';

export const CATEGORIES = [
	{ icon: IcPhoneBlack16, label: '휴대폰/통신' },
	{ icon: IcBottleBlack16, label: '유아용품' },
	{ icon: IcBeautyBlack16, label: '뷰티/건강' },
	{ icon: IcPaintBlack16, label: '시공/리모델링' },
	{ icon: IcBagBlack16, label: '가방/소품' },
	{ icon: IcRefrigeratorBlack16, label: '가전' },
	{ icon: IcHomeBlack16, label: '홈인테리어' },
	{ icon: IcHelmetBlack16, label: '자동차용품' },
	{ icon: IcBallBlack16, label: '스포츠/레저' },
	{ icon: IcJewelBlack16, label: '쥬얼리/시계' },
	{ icon: IcUnderwearBlack16, label: '속옷/잠옷' },
	{ icon: IcGameBlack16, label: '장난감/놀이' },
	{ icon: IcWatchBlack16, label: '패션잡화' },
];
