import {
	IcPhoneBlack16,
	IcBottleBlack16,
	IcBeautyBlack16,
	IcPaintBlack16,
	IcBagBlack16,
	IcRefrigeratorBlack16,
	IcHomeBlack16,
	IcHelmetBlack16,
	IcBallBlack16,
	IcJewelBlack16,
	IcGameBlack16,
	IcWatchBlack16,
	IcUnderwearBlack16,
	IcDogBlack16,
	IcShoesBlack16,
	IcOfficesuppliesBlack16,
	IcElectronicdevicesBlack16,
	IcFurnitureBlack16,
	IcToolBlack16,
	IcHomecamBlack16,
	IcManfashionBlack16,
	IcWomanfashionBlack16,
} from '@assets/icons/index';

export const CATEGORIES = Object.freeze([
	{ icon: IcPhoneBlack16, label: '휴대폰/통신' },
	{ icon: IcBottleBlack16, label: '유아용품' },
	{ icon: IcBeautyBlack16, label: '뷰티/건강' },
	{ icon: IcPaintBlack16, label: '시공/리모델링' },
	{ icon: IcBagBlack16, label: '가방/소품' },
	{ icon: IcRefrigeratorBlack16, label: '가전' },
	{ icon: IcHomeBlack16, label: '홈인테리어' },
	{ icon: IcHelmetBlack16, label: '자동차용품' },
	{ icon: IcBallBlack16, label: '스포츠/레저' },
	{ icon: IcJewelBlack16, label: '쥬얼리/시계' },
	{ icon: IcUnderwearBlack16, label: '속옷/잠옷' },
	{ icon: IcGameBlack16, label: '장난감/놀이' },
	{ icon: IcWatchBlack16, label: '패션잡화' },
	{ icon: IcDogBlack16, label: '반려동물' },
	{ icon: IcShoesBlack16, label: '신발' },
	{ icon: IcOfficesuppliesBlack16, label: '문구/사무용품' },
	{ icon: IcElectronicdevicesBlack16, label: '디지털용품' },
	{ icon: IcFurnitureBlack16, label: '가구' },
	{ icon: IcToolBlack16, label: '공구/도구' },
	{ icon: IcHomecamBlack16, label: '홈캠/도어룩' },
	{ icon: IcManfashionBlack16, label: '남성패션' },
	{ icon: IcWomanfashionBlack16, label: '여성패션' },
] as const);
