name: Auto Sync
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  sync:
    name: Sync forked repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_SYNC }}

      - name: Configure Git
        run: |
          git remote add forked_repo https://github.com/seong-hui/35-COLLABORATION-WEB-ALIEXPRESS
          git config user.name "seong-hui"
          git config user.email "msh9980@naver.com"

      - name: Push Changes to forked_repo
        run: git push forked_repo main
